my_list = [1, 'a', 2.0, True]
print(my_list)
print(my_list[0])
print(my_list[1])
print(len(my_list))
print(my_list[-1])
print(my_list[0:3])
print(my_list[:3])
print(my_list[2:])
print(my_list[::2])
print(my_list[1::2])
my_list[0] = 1.0
print(my_list)
my_list.append(False)
print(my_list)
print(my_list + [9, 10])
my_list += [9, 10]
print(my_list)
print(my_list[1:3])
my_list[1:3] = ['b', 'c']
print(my_list)
my_list[1:3] = ['d', 'e', 'f']
print(my_list)
my_list[1:4] = []
print(my_list)
my_list.remove(9)
print(my_list)
my_list.remove(True)
print(my_list)
print(bool(1.0))
my_list.remove(False)
print(my_list)
new_list = [1, 2, 3, 4]
print(new_list.pop())
print(new_list)
print(new_list.pop(0))
print(new_list)
point = (2.0, 3.0)
print(point[0])
print(point[1])
print("My name is %s" % "Keith")
print("My name is %s %s" % ("Keith", "Thomson"))
print(("Keith"))
print(("Keith",))
