print('this')
print("that")
print("double".find('s'))
print("double".find("u"))
print("double".find("bl"))
print("TesTinG".lower())
print("pass" + "word")
print("Ha" * 4)
print("Tab\tDelimited")
print("Tab\nDelimited")
print("Tab\\Delimited")
print("'Single' in Double")
print('"Double" in Single')
print("\"Double\" in Double")
print(4)
print(5.4)
print(2 + 2)
print(10 - 4)
print(5 / 3)
print(5.0 / 3)
print(5 // 3)
print(5.0 // 3)
print(3 * 9)
print(8 % 3)
print(int("1"))
print(float("1.0"))
print(str("5.6"))
print(str(5.6))
